apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
      volumes:
        - name: prometheus-storage-tsdb-volume
          persistentVolumeClaim:
            claimName: prometheus-tsdb-storage
