---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-tsdb-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: staging-prometheus-storage-class # kustomize does not supplies prefix.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-storage-class
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
parameters:
  type: pd-standard
  zones: asia-northeast1-a
  replication-type: none
