namespace: staging-monitoring
namePrefix: staging-
commonLabels:
  variant: staging
bases:
- ../../base
patches:
- prometheus/deployment.yaml
- prometheus/configmap.yaml
- prometheus/clusterRole.yaml
resources:
- prometheus/volume.yaml
configMapGenerator:
- name: prometheus-server-config
  behavior: merge
  literals:
    - tsdbRetention=48h
