namespace: development-monitoring
namePrefix: development-
commonLabels:
  variant: development
bases:
- ../../base
patches:
- prometheus/deployment.yaml
- prometheus/configmap.yaml
- prometheus/clusterRole.yaml
configMapGenerator:
- name: prometheus-server-config
  behavior: merge
  literals:
    - tsdbRetention=12h
