apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    name: alertmanager
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    deployment: alertmanager
  type: ClusterIP
