apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: prometheus
      annotations:
    spec:
      serviceAccountName: ex-gcp-k8s-prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.3.2
        imagePullPolicy: Always
        args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.enable-lifecycle"
        - "--storage.tsdb.retention=$(TSDB_RETENTION)"
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
        - name: TSDB_RETENTION
          valueFrom:
            configMapKeyRef:
              name: prometheus-server-config
              key: tsdbRetention
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
          readOnly: true
        - name: prometheus-storage-tsdb-volume
          mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-config
        - name: prometheus-storage-tsdb-volume
          emptyDir: {} # kustomize: development - emptyDir, staging, production - persistent disk
