namespace: monitoring
commonLabels:
  app: monitoring
resources:
- namespace.yaml
- prometheus/deployment.yaml
- prometheus/service.yaml
- prometheus/configmap.yaml
- prometheus/configmap-rule.yaml
- prometheus/clusterRole.yaml
- alertmanager/deployment.yaml
- alertmanager/service.yaml
- alertmanager/configmap.yaml
configMapGenerator:
- name: prometheus-server-config
  behavior: merge
  literals:
    - tsdbRetention=24h
- name: alertmanager-config
  behavior: merge
  literals:
    - dataRetention=24h
