namespace: monitoring
commonLabels:
  app: monitoring
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- namespace.yaml
- clusterRole.yaml
- alertmanager.yaml
- alertmanager-service.yaml
- alertmanager-config.yaml
configMapGenerator:
- name: prometheus-server-config
  behavior: merge
  literals:
    - tsdbRetention=24h
- name: alertmanager-config
  behavior: merge
  literals:
    - dataRetention=24h
